# Generated by Django 4.2.7 on 2023-12-04 20:45

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'Имя пользователя занято.'}, max_length=64, unique=True, validators=[account.validators.UsernameValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
